d ={}
d['8-1'] = {'tegund': "virkur", 'specials': []}
d['8-2'] = {'tegund': "virkur", 'specials': []}
d['8-3'] = {'tegund': "virkur", 'specials': []}
d['8-4'] = {'tegund': "virkur", 'specials': []}
d['8-5'] = {'tegund': "virkur", 'specials': []}
d['8-6'] = {'tegund': "helgi", 'specials': []}
d['8-7'] = {'tegund': "helgi", 'specials': []}
d['8-8'] = {'tegund': "virkur", 'specials': []}
d['8-9'] = {'tegund': "virkur", 'specials': []}
d['8-10'] = {'tegund': "virkur", 'specials': []}
d['8-11'] = {'tegund': "virkur", 'specials': []}
d['8-12'] = {'tegund': "virkur", 'specials': []}
d['8-13'] = {'tegund': "helgi", 'specials': []}
d['8-14'] = {'tegund': "helgi", 'specials': []}
d['8-15'] = {'tegund': "virkur", 'specials': []}
d['8-16'] = {'tegund': "virkur", 'specials': []}
d['8-17'] = {'tegund': "virkur", 'specials': []}
d['8-18'] = {'tegund': "virkur", 'specials': []}
d['8-19'] = {'tegund': "starfsdagur", 'specials': [("Starfsmannafundur kl. 9:00", "glyphicon glyphicon-bell"),("Töflubreytingar","glyphicon glyphicon-folder-open")]}
d['8-20'] = {'tegund': "helgi", 'specials': []}
d['8-21'] = {'tegund': "helgi", 'specials': []}
d['8-22'] = {'tegund': "starfsdagur", 'specials': [("Töflubreytingar","glyphicon glyphicon-folder-open")]}
d['8-23'] = {'tegund': "kennsludagur", 'specials': [("Kennsla hefst", "glyphicon glyphicon-alert")]}
d['8-24'] = {'tegund': "kennsludagur", 'specials': []}
d['8-25'] = {'tegund': "kennsludagur", 'specials': []}
d['8-26'] = {'tegund': "kennsludagur", 'specials': [("Nýnemadagur","glyphicon glyphicon-user")]}
d['8-27'] = {'tegund': "helgi", 'specials': []}
d['8-28'] = {'tegund': "helgi", 'specials': []}
d['8-29'] = {'tegund': "kennsldagur", 'specials': []}
d['8-30'] = {'tegund': "kennsludagur", 'specials': [("Foreldrafundur","glyphicon glyphicon-blackboard")]}
d['8-31'] = {'tegund': "kennsludagur", 'specials': []}

d['9-1'] = {'tegund': "kennsludagur", 'specials': [("Haustferð nýnema","glyphicon glyphicon-tent")]}
d['9-2'] = {'tegund': "kennsludagur", 'specials': [("Haustferð nýnema","glyphicon glyphicon-tent")]}
d['9-3'] = {'tegund': "helgi", 'specials': []}
d['9-4'] = {'tegund': "helgi", 'specials': []}
d['9-5'] = {'tegund': "kennsludagur", 'specials': []}
d['9-6'] = {'tegund': "kennsludagur", 'specials': [("Kennsla fjarnáms hefst", "glyphicon glyphicon-envelope")]}
d['9-7'] = {'tegund': "kennsludagur", 'specials': []}
d['9-8'] = {'tegund': "kennsludagur", 'specials': []}
d['9-9'] = {'tegund': "kennsludagur", 'specials': [("Eindagi áfangaúrsagnar", "glyphicon glyphicon-alert")]}
d['9-10'] = {'tegund': "helgi", 'specials': []}
d['9-11'] = {'tegund': "helgi", 'specials': []}
d['9-12'] = {'tegund': "kennsludagur", 'specials': []}
d['9-13'] = {'tegund': "kennsludagur", 'specials': []}
d['9-14'] = {'tegund': "kennsludagur", 'specials': []}
d['9-15'] = {'tegund': "kennsludagur", 'specials': []}
d['9-16'] = {'tegund': "kennsludagur", 'specials': [("Dagur íslenskrar náttúru", "glyphicon glyphicon-tree-deciduous"),("Haustferð starfsmanna", "glyphicon glyphicon-tent")]}
d['9-17'] = {'tegund': "helgi", 'specials': []}
d['9-18'] = {'tegund': "helgi", 'specials': []}
d['9-19'] = {'tegund': "kennsludagur", 'specials': [("Starfsmannafundur kl. 8:15", "glyphicon glyphicon-bell")]}
d['9-20'] = {'tegund': "kennsludagur", 'specials': []}
d['9-21'] = {'tegund': "kennsludagur", 'specials': []}
d['9-22'] = {'tegund': "kennsludagur", 'specials': []}
d['9-23'] = {'tegund': "kennsludagur", 'specials': []}
d['9-24'] = {'tegund': "helgi", 'specials': []}
d['9-25'] = {'tegund': "helgi", 'specials': []}
d['9-26'] = {'tegund': "kennsludagur", 'specials': []}
d['9-27'] = {'tegund': "kennsludagur", 'specials': []}
d['9-28'] = {'tegund': "kennsludagur", 'specials': []}
d['9-29'] = {'tegund': "kennsludagur", 'specials': []}
d['9-30'] = {'tegund': "kennsludagur", 'specials': []}

d['10-1'] = {'tegund': "helgi", 'specials': []}
d['10-2'] = {'tegund': "helgi", 'specials': []}
d['10-3'] = {'tegund': "kennsludagur", 'specials': []}
d['10-4'] = {'tegund': "kennsludagur", 'specials': []}
d['10-5'] = {'tegund': "kennsludagur", 'specials': []}
d['10-6'] = {'tegund': "kennsludagur", 'specials': []}
d['10-7'] = {'tegund': "kennsludagur", 'specials': []}
d['10-8'] = {'tegund': "helgi", 'specials': []}
d['10-9'] = {'tegund': "helgi", 'specials': []}
d['10-10'] = {'tegund': "kennsludagur", 'specials': []}
d['10-11'] = {'tegund': "kennsludagur", 'specials': []}
d['10-12'] = {'tegund': "kennsludagur", 'specials': []}
d['10-13'] = {'tegund': "kennsludagur", 'specials': []}
d['10-14'] = {'tegund': "kennsludagur", 'specials': []}
d['10-15'] = {'tegund': "helgi", 'specials': []}
d['10-16'] = {'tegund': "helgi", 'specials': []}
d['10-17'] = {'tegund': "kennsludagur", 'specials': [("Starfsmannafundur kl. 8:15", "glyphicon glyphicon-bell")]}
d['10-18'] = {'tegund': "kennsludagur", 'specials': [("Námskynning", "glyphicon glyphicon-blackboard")]}
d['10-19'] = {'tegund': "kennsludagur", 'specials': []}
d['10-20'] = {'tegund': "profadagur", 'specials': [("Námsmatsdagur", "glyphicon glyphicon-pencil")]}
d['10-21'] = {'tegund': "profadagur", 'specials': [("Námsmatsdagur", "glyphicon glyphicon-pencil")]}
d['10-22'] = {'tegund': "helgi", 'specials': [("Haustfrí", "glyphicon glyphicon-home")]}
d['10-23'] = {'tegund': "helgi", 'specials': [("Haustfrí", "glyphicon glyphicon-home")]}
d['10-24'] = {'tegund': "helgi", 'specials': [("Haustfrí", "glyphicon glyphicon-home")]}
d['10-25'] = {'tegund': "kennsludagur", 'specials': []}
d['10-26'] = {'tegund': "kennsludagur", 'specials': []}
d['10-27'] = {'tegund': "kennsludagur", 'specials': []}
d['10-28'] = {'tegund': "kennsludagur", 'specials': []}
d['10-29'] = {'tegund': "helgi", 'specials': []}
d['10-30'] = {'tegund': "helgi", 'specials': []}
d['10-31'] = {'tegund': "kennsludagur", 'specials': []}

d['11-1'] = {'tegund': "kennsludagur", 'specials': []}
d['11-2'] = {'tegund': "kennsludagur", 'specials': []}
d['11-3'] = {'tegund': "kennsludagur", 'specials': []}
d['11-4'] = {'tegund': "kennsludagur", 'specials': []}
d['11-5'] = {'tegund': "helgi", 'specials': []}
d['11-6'] = {'tegund': "helgi", 'specials': []}
d['11-7'] = {'tegund': "kennsludagur", 'specials': []}
d['11-8'] = {'tegund': "kennsludagur", 'specials': []}
d['11-9'] = {'tegund': "kennsludagur", 'specials': []}
d['11-10'] = {'tegund': "kennsludagur", 'specials': []}
d['11-11'] = {'tegund': "kennsludagur", 'specials': []}
d['11-12'] = {'tegund': "helgi", 'specials': []}
d['11-13'] = {'tegund': "helgi", 'specials': []}
d['11-14'] = {'tegund': "kennsludagur", 'specials': [("Starfsmannafundur kl. 8:15", "glyphicon glyphicon-bell")]}
d['11-15'] = {'tegund': "kennsludagur", 'specials': []}
d['11-16'] = {'tegund': "kennsludagur", 'specials': []}
d['11-17'] = {'tegund': "kennsludagur", 'specials': []}
d['11-18'] = {'tegund': "kennsludagur", 'specials': []}
d['11-19'] = {'tegund': "helgi", 'specials': []}
d['11-20'] = {'tegund': "helgi", 'specials': []}
d['11-21'] = {'tegund': "kennsludagur", 'specials': []}
d['11-22'] = {'tegund': "kennsludagur", 'specials': []}
d['11-23'] = {'tegund': "kennsludagur", 'specials': []}
d['11-24'] = {'tegund': "kennsludagur", 'specials': []}
d['11-25'] = {'tegund': "kennsludagur", 'specials': [("Dimision", "glyphicon glyphicon-bullhorn")]}
d['11-26'] = {'tegund': "helgi", 'specials': []}
d['11-27'] = {'tegund': "helgi", 'specials': []}
d['11-28'] = {'tegund': "kennsludagur", 'specials': []}
d['11-29'] = {'tegund': "kennsludagur", 'specials': []}
d['11-30'] = {'tegund': "kennsludagur", 'specials': []}

d['12-1'] = {'tegund': "kennsludagur", 'specials': [("Síðasti kennsludagur", "glyphicon glyphicon-dashboard")]}
d['12-2'] = {'tegund': "profadagur", 'specials': [("Námsmatsdagur", "glyphicon glyphicon-pencil")]}
d['12-3'] = {'tegund': "helgi", 'specials': []}
d['12-4'] = {'tegund': "helgi", 'specials': []}
d['12-5'] = {'tegund': "profadagur", 'specials': [("Próf hefjast", "glyphicon glyphicon-alert")]}
d['12-6'] = {'tegund': "profadagur", 'specials': []}
d['12-7'] = {'tegund': "profadagur", 'specials': []}
d['12-8'] = {'tegund': "profadagur", 'specials': []}
d['12-9'] = {'tegund': "profadagur", 'specials': []}
d['12-10'] = {'tegund': "helgi", 'specials': []}
d['12-11'] = {'tegund': "helgi", 'specials': []}
d['12-12'] = {'tegund': "profadagur", 'specials': []}
d['12-13'] = {'tegund': "profadagur", 'specials': []}
d['12-14'] = {'tegund': "profadagur", 'specials': [("Endurtektarpróf kl. 8:30", "glyphicon glyphicon-alert"),("Prófsýning og val kl. 11:00-14:00", "glyphicon glyphicon-blackboard")]}
d['12-15'] = {'tegund': "starfsdagur", 'specials': []}
d['12-16'] = {'tegund': "starfsdagur", 'specials': []}
d['12-17'] = {'tegund': "starfsdagur", 'specials': [("Æfing fyrir brautskráningu kl. 16:00", "glyphicon glyphicon-bullhorn")]}
d['12-18'] = {'tegund': "starfsdagur", 'specials': [("Útskrift kl. 13:00","glyphicon glyphicon-education")]}
d['12-19'] = {'tegund': "helgi", 'specials': []}
d['12-20'] = {'tegund': "helgi", 'specials': []}
d['12-21'] = {'tegund': "helgi", 'specials': []}
d['12-22'] = {'tegund': "helgi", 'specials': []}
d['12-23'] = {'tegund': "helgi", 'specials': []}
d['12-24'] = {'tegund': "helgi", 'specials': []}
d['12-25'] = {'tegund': "helgi", 'specials': []}
d['12-26'] = {'tegund': "helgi", 'specials': []}
d['12-27'] = {'tegund': "helgi", 'specials': []}
d['12-28'] = {'tegund': "helgi", 'specials': []}
d['12-29'] = {'tegund': "helgi", 'specials': []}
d['12-30'] = {'tegund': "helgi", 'specials': []}
d['12-31'] = {'tegund': "helgi", 'specials': []}

d['1-1'] = {'tegund': "helgi", 'specials': []}
d['1-2'] = {'tegund': "helgi", 'specials': []}
d['1-3'] = {'tegund': "helgi", 'specials': []}
d['1-4'] = {'tegund': "starfsdagur", 'specials': [("Starfsmannafundur kl. 9:00", "glyphicon glyphicon-bell"),("Töflubreytingar","glyphicon glyphicon-folder-open")]}
d['1-5'] = {'tegund': "starfsdagur", 'specials': [("Töflubreytingar","glyphicon glyphicon-folder-open")]}
d['1-6'] = {'tegund': "kennsludagur", 'specials': [("Kennsla hefst", "glyphicon glyphicon-alert")]}
d['1-7'] = {'tegund': "helgi", 'specials': []}
d['1-8'] = {'tegund': "helgi", 'specials': []}
d['1-9'] = {'tegund': "kennsludagur", 'specials': []}
d['1-10'] = {'tegund': "kennsludagur", 'specials': []}
d['1-11'] = {'tegund': "kennsludagur", 'specials': []}
d['1-12'] = {'tegund': "kennsludagur", 'specials': []}
d['1-13'] = {'tegund': "kennsludagur", 'specials': []}
d['1-14'] = {'tegund': "helgi", 'specials': []}
d['1-15'] = {'tegund': "helgi", 'specials': []}
d['1-16'] = {'tegund': "kennsludagur", 'specials': []}
d['1-17'] = {'tegund': "kennsludagur", 'specials': []}
d['1-18'] = {'tegund': "kennsludagur", 'specials': []}
d['1-19'] = {'tegund': "kennsludagur", 'specials': []}
d['1-20'] = {'tegund': "kennsludagur", 'specials': []}
d['1-21'] = {'tegund': "helgi", 'specials': []}
d['1-22'] = {'tegund': "helgi", 'specials': []}
d['1-23'] = {'tegund': "kennsludagur", 'specials': []}
d['1-24'] = {'tegund': "kennsludagur", 'specials': []}
d['1-25'] = {'tegund': "kennsludagur", 'specials': []}
d['1-26'] = {'tegund': "kennsludagur", 'specials': []}
d['1-27'] = {'tegund': "kennsludagur", 'specials': []}
d['1-28'] = {'tegund': "helgi", 'specials': []}
d['1-29'] = {'tegund': "helgi", 'specials': []}
d['1-30'] = {'tegund': "kennsludagur", 'specials': []}
d['1-31'] = {'tegund': "kennsludagur", 'specials': []}

d['2-1'] = {'tegund': "kennsludagur", 'specials': []}
d['2-2'] = {'tegund': "kennsludagur", 'specials': []}
d['2-3'] = {'tegund': "kennsludagur", 'specials': []}
d['2-4'] = {'tegund': "helgi", 'specials': []}
d['2-5'] = {'tegund': "helgi", 'specials': []}
d['2-6'] = {'tegund': "kennsludagur", 'specials': []}
d['2-7'] = {'tegund': "kennsludagur", 'specials': []}
d['2-8'] = {'tegund': "kennsludagur", 'specials': []}
d['2-9'] = {'tegund': "kennsludagur", 'specials': []}
d['2-10'] = {'tegund': "kennsludagur", 'specials': []}
d['2-11'] = {'tegund': "helgi", 'specials': []}
d['2-12'] = {'tegund': "helgi", 'specials': []}
d['2-13'] = {'tegund': "kennsludagur", 'specials': []}
d['2-14'] = {'tegund': "kennsludagur", 'specials': []}
d['2-15'] = {'tegund': "kennsludagur", 'specials': []}
d['2-16'] = {'tegund': "kennsludagur", 'specials': []}
d['2-17'] = {'tegund': "kennsludagur", 'specials': []}
d['2-18'] = {'tegund': "helgi", 'specials': []}
d['2-19'] = {'tegund': "helgi", 'specials': []}
d['2-20'] = {'tegund': "kennsludagur", 'specials': []}
d['2-21'] = {'tegund': "kennsludagur", 'specials': []}
d['2-22'] = {'tegund': "kennsludagur", 'specials': []}
d['2-23'] = {'tegund': "kennsludagur", 'specials': []}
d['2-24'] = {'tegund': "kennsludagur", 'specials': []}
d['2-25'] = {'tegund': "helgi", 'specials': []}
d['2-26'] = {'tegund': "helgi", 'specials': []}
d['2-27'] = {'tegund': "kennsludagur", 'specials': []}
d['2-28'] = {'tegund': "kennsludagur", 'specials': []}

d['3-1'] = {'tegund': "starfsdagur", 'specials': [("Árdagar", "glyphicon glyphicon-bullhorn")]}
d['3-2'] = {'tegund': "starfsdagur", 'specials': [("Árdagar", "glyphicon glyphicon-bullhorn")]}
d['3-3'] = {'tegund': "kennsludagur", 'specials': [("Skólaráðstefna með FB", "glyphicon glyphicon-blackboard")]}
d['3-4'] = {'tegund': "helgi", 'specials': []}
d['3-5'] = {'tegund': "helgi", 'specials': []}
d['3-6'] = {'tegund': "kennsludagur", 'specials': []}
d['3-7'] = {'tegund': "kennsludagur", 'specials': []}
d['3-8'] = {'tegund': "kennsludagur", 'specials': []}
d['3-9'] = {'tegund': "kennsludagur", 'specials': []}
d['3-10'] = {'tegund': "kennsludagur", 'specials': []}
d['3-11'] = {'tegund': "helgi", 'specials': []}
d['3-12'] = {'tegund': "helgi", 'specials': []}
d['3-13'] = {'tegund': "profadagur", 'specials': [("Námsmatsdagur", "glyphicon glyphicon-pencil")]}
d['3-14'] = {'tegund': "kennsludagur", 'specials': []}
d['3-15'] = {'tegund': "kennsludagur", 'specials': []}
d['3-16'] = {'tegund': "kennsludagur", 'specials': []}
d['3-17'] = {'tegund': "kennsludagur", 'specials': []}
d['3-18'] = {'tegund': "helgi", 'specials': []}
d['3-19'] = {'tegund': "helgi", 'specials': []}
d['3-20'] = {'tegund': "kennsludagur", 'specials': []}
d['3-21'] = {'tegund': "kennsludagur", 'specials': []}
d['3-22'] = {'tegund': "kennsludagur", 'specials': []}
d['3-23'] = {'tegund': "kennsludagur", 'specials': []}
d['3-24'] = {'tegund': "kennsludagur", 'specials': []}
d['3-25'] = {'tegund': "helgi", 'specials': []}
d['3-26'] = {'tegund': "helgi", 'specials': []}
d['3-27'] = {'tegund': "kennsludagur", 'specials': []}
d['3-28'] = {'tegund': "kennsludagur", 'specials': []}
d['3-29'] = {'tegund': "kennsludagur", 'specials': []}
d['3-30'] = {'tegund': "kennsludagur", 'specials': []}
d['3-31'] = {'tegund': "kennsludagur", 'specials': []}

d['4-1'] = {'tegund': "helgi", 'specials': []}
d['4-2'] = {'tegund': "helgi", 'specials': []}
d['4-3'] = {'tegund': "kennsludagur", 'specials': []}
d['4-4'] = {'tegund': "kennsludagur", 'specials': []}
d['4-5'] = {'tegund': "kennsludagur", 'specials': []}
d['4-6'] = {'tegund': "kennsludagur", 'specials': []}
d['4-7'] = {'tegund': "kennsludagur", 'specials': []}
d['4-8'] = {'tegund': "helgi", 'specials': []}
d['4-9'] = {'tegund': "helgi", 'specials': [("Pálmasunnudagur", "glyphicon glyphicon-leaf")]}
d['4-10'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-11'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-12'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-13'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-14'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-15'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-16'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-17'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-18'] = {'tegund': "helgi", 'specials': [("Páskafrí", "glyphicon glyphicon-home")]}
d['4-19'] = {'tegund': "kennsludagur", 'specials': []}
d['4-20'] = {'tegund': "helgi", 'specials': [("Sumardagurinn fyrsti", "glyphicon glyphicon-home")]}
d['4-21'] = {'tegund': "kennsludagur", 'specials': []}
d['4-22'] = {'tegund': "helgi", 'specials': []}
d['4-23'] = {'tegund': "helgi", 'specials': []}
d['4-24'] = {'tegund': "kennsludagur", 'specials': []}
d['4-25'] = {'tegund': "kennsludagur", 'specials': []}
d['4-26'] = {'tegund': "kennsludagur", 'specials': []}
d['4-27'] = {'tegund': "kennsludagur", 'specials': []}
d['4-28'] = {'tegund': "kennsludagur", 'specials': []}
d['4-29'] = {'tegund': "helgi", 'specials': []}
d['4-30'] = {'tegund': "helgi", 'specials': []}

d['5-1'] = {'tegund': "helgi", 'specials': [("Hátíðisdagur verkamanna", "glyphicon glyphicon-flag")]}
d['5-2'] = {'tegund': "kennsludagur", 'specials': []}
d['5-3'] = {'tegund': "kennsludagur", 'specials': []}
d['5-4'] = {'tegund': "kennsludagur", 'specials': []}
d['5-5'] = {'tegund': "kennsludagur", 'specials': [("Síðasti kennsludagur", "glyphicon glyphicon-dashboard")]}
d['5-6'] = {'tegund': "helgi", 'specials': []}
d['5-7'] = {'tegund': "helgi", 'specials': []}
d['5-8'] = {'tegund': "profadagur", 'specials': [("Próf hefjast", "glyphicon glyphicon-alert")]}
d['5-9'] = {'tegund': "profadagur", 'specials': []}
d['5-10'] = {'tegund': "profadagur", 'specials': []}
d['5-11'] = {'tegund': "profadagur", 'specials': []}
d['5-12'] = {'tegund': "profadagur", 'specials': []}
d['5-13'] = {'tegund': "helgi", 'specials': []}
d['5-14'] = {'tegund': "helgi", 'specials': []}
d['5-15'] = {'tegund': "profadagur", 'specials': []}
d['5-16'] = {'tegund': "profadagur", 'specials': []}
d['5-17'] = {'tegund': "profadagur", 'specials': []}
d['5-18'] = {'tegund': "profadagur", 'specials': []}
d['5-19'] = {'tegund': "profadagur", 'specials': []}
d['5-20'] = {'tegund': "helgi", 'specials': []}
d['5-21'] = {'tegund': "helgi", 'specials': []}
d['5-22'] = {'tegund': "profadagur", 'specials': []}
d['5-23'] = {'tegund': "profadagur", 'specials': [("Prófsýning kl. 11:00-13:00", "glyphicon glyphicon-blackboard")]}
d['5-24'] = {'tegund': "starfsdagur", 'specials': []}
d['5-25'] = {'tegund': "starfsdagur", 'specials': []}
d['5-26'] = {'tegund': "starfsdagur", 'specials': [("Æfing fyrir brautskráningu kl. 16:00", "glyphicon glyphicon-bullhorn")]}
d['5-27'] = {'tegund': "starfsdagur", 'specials': [("Brautskráning kl. 13:00", "glyphicon glyphicon-education")]}
d['5-28'] = {'tegund': "helgi", 'specials': []}
d['5-29'] = {'tegund': "starfsdagur", 'specials': [("Starfsmannafundur kl. ??", "glyphicon glyphicon-bell")]}
d['5-30'] = {'tegund': "virkur", 'specials': []}
d['5-31'] = {'tegund': "virkur", 'specials': []}
